export enum Tiles {
  STARTING_TILE = "STARTING_TILE",
  ENDING_TILE = "ENDING_TILE",
  BLOCK_TILE = "BLOCK_TILE",
  EMPTY_TILE = "EMPTY_TILE",
}

export enum SolveGraph {
  STARTING_TILE = "STARTING_TILE",
  ENDING_TILE = "ENDING_TILE",
  BLOCK_TILE = "BLOCK_TILE",
  EMPTY_TILE = "EMPTY_TILE",
  PATH_TILE = "PATH_TILE",
  VISITED_LIST_TILE = "VISITED_LIST_TILE",
}
